resource_destination: fix crash
I saw this crash locally:

```
Stack trace from the terraform-provider-lightstep_v1.70.4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x16cffea]

goroutine 92 [running]:
github.com/lightstep/terraform-provider-lightstep/lightstep.resourceDestinationRead({0x19825c8, 0xc0005f4180}, 0xc0002da280, {0x183b740?, 0xc00029c8a0})
	github.com/lightstep/terraform-provider-lightstep/lightstep/resource_destination.go:22 +0x18a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000bf960, {0x1982600, 0xc0004607e0}, 0xd?, {0x183b740, 0xc00029c8a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000bf960, {0x1982600, 0xc0004607e0}, 0xc00012c5b0, {0x183b740, 0xc00029c8a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000419e78, {0x1982600?, 0xc0004606c0?}, 0xc0002de100)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00020ebe0, {0x1982600?, 0xc0002c5da0?}, 0xc000088de0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1827ca0?, 0xc00020ebe0}, {0x1982600, 0xc0002c5da0}, 0xc0000b05b0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002321e0, {0x1986080, 0xc0004941a0}, 0xc0002797a0, 0xc000425710, 0x1e27f70, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0002321e0, {0x1986080, 0xc0004941a0}, 0xc0002797a0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-lightstep_v1.70.4 plugin crashed!
```

I believe what happened here is that `client.Do` failed and returned
a nil `*http.Response`: https://github.com/lightstep/terraform-provider-lightstep/blob/e17c301f9b06a553941c91e848f2c89748ba284b/client/client.go#L141

So that's the reason for the nil check on the Response.

However, I think the interface assertion could also result in a panic
if, for example, json.Unmarshal fails: https://github.com/lightstep/terraform-provider-lightstep/blob/e17c301f9b06a553941c91e848f2c89748ba284b/client/destinations.go#L71

So change both assumptions: do not assume the interface assertion will
succeed and do not assume, even if it does, that the `*http.Response` is
non-nil.